package com.example.invoice.export_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "pdf_documents")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PdfDocument {

    /** Generated by invoice-service, not here: it is the correlation key. */
    @Id
    @Column(name = "request_id")
    private UUID requestId;

    @Column(name = "invoice_id", nullable = false)
    private Long invoiceId;

    /**
     * bytea, not @Lob. @Lob on a byte[] makes Hibernate expect a Postgres large
     * object (oid), which is stored outside the table and only removed by an
     * explicit lo_unlink — so every download would leak one. bytea is deleted
     * with its row, which is the whole storage strategy here.
     *
     * Lazy so listing or counting documents does not pull every PDF into
     * memory; only the download path touches the bytes.
     */
    @Basic(fetch = FetchType.LAZY)
    @Column(nullable = false, columnDefinition = "bytea")
    private byte[] content;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}