-- Transactional outbox. Domain writes and event writes commit together, so a
-- broker outage delays events rather than failing writes.
--
-- The table is per-service; only the dispatcher code is shared via common.

CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    topic           VARCHAR(128) NOT NULL,
    event_key       VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT now(),
    published_at    TIMESTAMP(6),
    attempts        INTEGER      NOT NULL DEFAULT 0,
    last_error      TEXT,
    next_attempt_at TIMESTAMP(6)
);

-- Partial index covering the dispatcher's full predicate, so it stays small as
-- published rows accumulate.
CREATE INDEX idx_outbox_pending
    ON outbox_events (next_attempt_at, id)
    WHERE published_at IS NULL;

CREATE INDEX idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);