-- Outbox and inbox, once.
--
-- In the distributed topology each service migrates its own copy of these into
-- its own database — five outbox_events tables, three processed_events. Here
-- there is one persistence unit, so the shared entities in common.outbox and
-- common.inbox map to one table each. The schema is unchanged: it is the
-- backoff-era shape that customer, import and archive share byte for byte and
-- that invoice and export converge on.
--
-- Consequence worth knowing: processed_events is now global, and its key is the
-- publishing service's event id, not the consumer's. Two consumers of one topic
-- would see each other's rows and the second would skip. No topic has two
-- consumers today, and the in-process publisher routes each to exactly one, so
-- this holds — but it holds by assumption, not by construction.

CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    topic           VARCHAR(128) NOT NULL,
    event_key       VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT now(),
    published_at    TIMESTAMP(6),
    attempts        INTEGER      NOT NULL DEFAULT 0,
    last_error      TEXT,
    next_attempt_at TIMESTAMP(6)
);

-- Partial index covering the dispatcher's full predicate: unpublished, and due.
CREATE INDEX idx_outbox_pending
    ON outbox_events (next_attempt_at, id)
    WHERE published_at IS NULL;

CREATE INDEX idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);

CREATE TABLE processed_events (
    event_id     VARCHAR(128) PRIMARY KEY,
    event_type   VARCHAR(64),
    processed_at TIMESTAMP(6) NOT NULL DEFAULT now()
);

CREATE INDEX idx_processed_events_processed_at ON processed_events (processed_at);