-- customer-service. Unchanged from its own V1__baseline.sql.

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,

    CONSTRAINT uk_customers_email UNIQUE (email)
);