-- invoice-service. Its V1 baseline, plus V4's pdf_requests. V2 and V3 are the
-- outbox and its backoff column, already in V1 here in final form.
--
-- local_customers is the read model invoice-service builds from customer
-- events. It sits beside `customers` in the same database now, holding the same
-- rows — an artefact of consolidating services that each projected their own
-- copy. Kept rather than collapsed: the projection is what the event flow
-- exercises, and removing it would make the deployed system diverge from the
-- developed one in behaviour rather than only in topology.

CREATE TABLE local_customers (
    customer_id BIGINT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL
);

CREATE TABLE invoices (
    invoice_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT        NOT NULL,
    invoice_date   DATE          NOT NULL,
    payment_status VARCHAR(32)   NOT NULL,
    archived       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP(6)  NOT NULL,
    total_amount   NUMERIC(19,2) NOT NULL,
    content_hash   VARCHAR(64)   NOT NULL,

    CONSTRAINT uk_invoices_content_hash UNIQUE (content_hash),
    CONSTRAINT ck_invoices_payment_status
        CHECK (payment_status IN ('PENDING','OVERDUE','SUCCESSFUL','FAILED'))
);

CREATE TABLE invoice_items (
    invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT        NOT NULL,
    description     VARCHAR(255)  NOT NULL,
    quantity        INTEGER       NOT NULL,
    unit_price      NUMERIC(19,2) NOT NULL,
    total_price     NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_invoice_items_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE CASCADE,
    CONSTRAINT ck_invoice_items_quantity CHECK (quantity >= 1)
);

CREATE TABLE pdf_requests (
    request_id   UUID PRIMARY KEY,
    invoice_id   BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_pdf_requests_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE CASCADE
);

CREATE INDEX idx_invoices_customer_id     ON invoices (customer_id);
CREATE INDEX idx_invoices_invoice_date    ON invoices (invoice_date);
CREATE INDEX idx_invoices_archived        ON invoices (archived);
CREATE INDEX idx_invoice_items_invoice    ON invoice_items (invoice_id);
CREATE INDEX idx_pdf_requests_invoice_id  ON pdf_requests (invoice_id);