-- import-service. Unchanged from its own V1__baseline.sql.
--
-- name and email are denormalised onto the invoice because the CSV carries them
-- per row; there is no import_customers table. Now that `customers` sits in the
-- same database this is the third copy of customer data here — recorded in the
-- log as the least defensible one, and the CSV contract is what should change.

CREATE TABLE import_invoices (
    invoice_id     BIGINT PRIMARY KEY,
    customer_id    BIGINT        NOT NULL,
    name           VARCHAR(255)  NOT NULL,
    email          VARCHAR(255)  NOT NULL,
    invoice_date   DATE          NOT NULL,
    payment_status VARCHAR(32)   NOT NULL,
    total_amount   NUMERIC(19,2) NOT NULL,
    content_hash   VARCHAR(64)   NOT NULL,

    CONSTRAINT ck_import_invoices_payment_status
        CHECK (payment_status IN ('PENDING','OVERDUE','SUCCESSFUL','FAILED'))
);

CREATE TABLE import_invoice_items (
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL,
    description VARCHAR(255)  NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(19,2) NOT NULL,
    total_price NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_import_invoice_items_invoice
        FOREIGN KEY (invoice_id) REFERENCES import_invoices (invoice_id) ON DELETE CASCADE,
    CONSTRAINT ck_import_invoice_items_quantity CHECK (quantity >= 1)
);

CREATE INDEX idx_import_invoices_customer_id  ON import_invoices (customer_id);
CREATE INDEX idx_import_invoice_items_invoice ON import_invoice_items (invoice_id);