-- archive-service. Unchanged from its own V1__baseline.sql, including the
-- duplicate relationship on items: invoice_id is the business key the mapper
-- actually sets, archived_invoice_id is the FK the entity declares and nothing
-- populates. ArchiveService works around it. Copied faithfully rather than
-- fixed here — the fix belongs in the module's own migration, not in an
-- assembly artefact that would then disagree with it.

CREATE TABLE archived_invoices (
    archived_invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT        NOT NULL,
    customer_id         BIGINT        NOT NULL,
    name                VARCHAR(255)  NOT NULL,
    email               VARCHAR(255)  NOT NULL,
    invoice_date        DATE          NOT NULL,
    payment_status      VARCHAR(32),
    total_amount        NUMERIC(19,2) NOT NULL,
    event_type          VARCHAR(32),

    CONSTRAINT uk_archived_invoices_invoice_id UNIQUE (invoice_id),
    CONSTRAINT ck_archived_invoices_event_type
        CHECK (event_type IN ('MANUAL_ARCHIVE','AUTO_ARCHIVE','UNARCHIVE'))
);

CREATE TABLE archived_invoice_items (
    archived_invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id               BIGINT        NOT NULL,
    archived_invoice_id      BIGINT,
    description              VARCHAR(255)  NOT NULL,
    quantity                 INTEGER       NOT NULL,
    unit_price               NUMERIC(19,2) NOT NULL,
    total_price              NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_archived_invoice_items_invoice
        FOREIGN KEY (archived_invoice_id)
        REFERENCES archived_invoices (archived_invoice_id) ON DELETE CASCADE,
    CONSTRAINT ck_archived_invoice_items_quantity CHECK (quantity >= 1)
);

CREATE INDEX idx_archived_invoices_customer_id  ON archived_invoices (customer_id);
CREATE INDEX idx_archived_invoices_invoice_date ON archived_invoices (invoice_date);
CREATE INDEX idx_archived_invoice_items_invoice ON archived_invoice_items (invoice_id);
CREATE INDEX idx_archived_invoice_items_archive ON archived_invoice_items (archived_invoice_id);