-- Baseline schema for export-service.
-- Tables renamed to plural for consistency with the rest of the system;
-- the matching @Table annotations change with this migration.

CREATE TABLE export_customers (
    customer_id BIGINT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL
);

CREATE TABLE export_invoices (
    invoice_id     BIGINT PRIMARY KEY,
    customer_id    BIGINT        NOT NULL,
    invoice_date   DATE          NOT NULL,
    payment_status VARCHAR(32),
    archived       BOOLEAN,
    created_at     TIMESTAMP(6),
    total_amount   NUMERIC(19,2) NOT NULL,
    content_hash   VARCHAR(64),

    CONSTRAINT fk_export_invoices_customer
        FOREIGN KEY (customer_id) REFERENCES export_customers (customer_id),
    CONSTRAINT ck_export_invoices_payment_status
        CHECK (payment_status IN ('PENDING','OVERDUE','SUCCESSFUL','FAILED'))
);

CREATE TABLE export_invoice_items (
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL,
    description VARCHAR(255)  NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(19,2) NOT NULL,
    total_price NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_export_invoice_items_invoice
        FOREIGN KEY (invoice_id) REFERENCES export_invoices (invoice_id) ON DELETE CASCADE,
    CONSTRAINT ck_export_invoice_items_quantity CHECK (quantity >= 1)
);

CREATE INDEX idx_export_invoices_customer_id  ON export_invoices (customer_id);
CREATE INDEX idx_export_invoices_invoice_date ON export_invoices (invoice_date);
CREATE INDEX idx_export_invoice_items_invoice ON export_invoice_items (invoice_id);