-- Generated PDFs, held only between generation and first download.
--
-- bytea rather than a file: Render's disk is ephemeral, so a file written by
-- one instance is invisible to the next and gone after a restart. The database
-- is the only durable option, and deleting on download keeps the cost to one
-- row for the length of one user's wait.
--
-- No FK to pdf_requests: that table lives in invoicedb. The requestId is the
-- correlation key across the two services and is generated by invoice-service.

CREATE TABLE pdf_documents (
    request_id UUID PRIMARY KEY,
    invoice_id BIGINT       NOT NULL,
    content    BYTEA        NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT now()
);

-- Supports the cleanup of PDFs nobody ever downloads.
CREATE INDEX idx_pdf_documents_created_at ON pdf_documents (created_at);