-- Baseline schema for invoice-service.
--
-- Derived from the schema ddl-auto produced, then cleaned: pg_dump artifacts
-- removed, Hibernate's generated constraint names replaced with readable ones,
-- and indexes added on the columns the queries actually filter by. Postgres
-- does not index foreign keys automatically.

CREATE TABLE local_customers (
    customer_id BIGINT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL
);

CREATE TABLE invoices (
    invoice_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT        NOT NULL,
    invoice_date   DATE          NOT NULL,
    payment_status VARCHAR(32)   NOT NULL,
    archived       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP(6)  NOT NULL,
    total_amount   NUMERIC(19,2) NOT NULL,
    content_hash   VARCHAR(64)      NOT NULL,

    CONSTRAINT uk_invoices_content_hash UNIQUE (content_hash),
    CONSTRAINT ck_invoices_payment_status
        CHECK (payment_status IN ('PENDING','OVERDUE','SUCCESSFUL','FAILED'))
);

CREATE TABLE invoice_items (
    invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT        NOT NULL,
    description     VARCHAR(255)  NOT NULL,
    quantity        INTEGER       NOT NULL,
    unit_price      NUMERIC(19,2) NOT NULL,
    total_price     NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_invoice_items_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE CASCADE,
    CONSTRAINT ck_invoice_items_quantity CHECK (quantity >= 1)
);

-- Supports the InvoiceRepository.search filters and the entity-graph fetch.
CREATE INDEX idx_invoices_customer_id  ON invoices (customer_id);
CREATE INDEX idx_invoices_invoice_date ON invoices (invoice_date);
CREATE INDEX idx_invoices_archived     ON invoices (archived);
CREATE INDEX idx_invoice_items_invoice ON invoice_items (invoice_id);