-- Transactional outbox.
--
-- Domain writes and event writes happen in one local transaction, so an event
-- can never be lost after a successful commit. A scheduled dispatcher owns
-- delivery. Kafka being unavailable delays events; it no longer fails writes.

CREATE TABLE outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    topic          VARCHAR(128) NOT NULL,
    event_key      VARCHAR(128) NOT NULL,
    event_type     VARCHAR(64)  NOT NULL,
    payload        TEXT         NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL DEFAULT now(),
    published_at   TIMESTAMP(6),
    attempts       INTEGER      NOT NULL DEFAULT 0,
    last_error     TEXT
);

-- The dispatcher's only query: unpublished rows, oldest first. Partial index
-- so it stays small as published rows accumulate.
CREATE INDEX idx_outbox_unpublished
    ON outbox_events (id)
    WHERE published_at IS NULL;

CREATE INDEX idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);